INSERT IGNORE INTO professions (code, display_name, category, active) VALUES
('WAITER',                   'Mesero/a',                  'Gastronomía',           TRUE),
('CHEF',                     'Chef/Cocinero',              'Gastronomía',           TRUE),
('BARTENDER',                'Bartender',                  'Gastronomía',           TRUE),
('BARISTA',                  'Barista',                    'Gastronomía',           TRUE),
('ELECTRICIAN',              'Electricista',               'Hogar y mantenimiento', TRUE),
('PLUMBER',                  'Plomero/a',                  'Hogar y mantenimiento', TRUE),
('PAINTER',                  'Pintor/a',                   'Hogar y mantenimiento', TRUE),
('CARPENTER',                'Carpintero/a',               'Hogar y mantenimiento', TRUE),
('CONSTRUCTION_WORKER',      'Obrero de Construcción',     'Hogar y mantenimiento', TRUE),
('GARDENER',                 'Jardinero/a',                'Hogar y mantenimiento', TRUE),
('AIR_CONDITIONING_TECHNICIAN', 'Instalador de A.A',      'Hogar y mantenimiento', TRUE),
('CLEANER',                  'Personal de Limpieza',       'Hogar y mantenimiento', TRUE),
('PILATES',                  'Instructora de pilates',     'Salud y bienestar',     TRUE),
('HAIRDRESSER',              'Peluquero/a',                'Belleza',               TRUE),
('MECHANIC',                 'Mecánico/a',                 'Servicios',             TRUE),
('DRIVER',                   'Conductor',                  'Servicios',             TRUE),
('SECURITY',                 'Personal de seguridad',      'Servicios',             TRUE),
('RECEPTIONIST',             'Recepcionista',              'Servicios',             TRUE),
('OTHER',                    'Otro',                       NULL,                    TRUE);
